return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "gopls",
        "clang-format",
        "biome",
        "deno",
        "angular-language-server",
        "bash-language-server",
        "clangd",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "gitlab-ci-ls",
        "hadolint",
        "html-lsp",
        "intelephense",
        "json-lsp",
        "jsonlint",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "prettier",
        "shfmt",
        "stylua",
        "typescript-language-server",
        "yaml-language-server",
      },
    },
  },
}
